export enum NotificationType {
  SONG_FEAT_REQUEST = 'SONG_FEAT_REQUEST',
  SONG_PUBLISHED = 'SONG_PUBLISHED',
  GENERAL = 'GENERAL',
  NEW_FOLLOW = 'NEW_FOLLOW',
  NEW_LIKE = 'NEW_LIKE',
  NEW_SONG_RELEASE = 'NEW_SONG_RELEASE'
}
