export enum RoleName {
  USER = 'USER',
  ARTIST = 'ARTIST',
  ADMIN = 'ADMIN',
  SUPPER_ADMIN = 'SUPPER ADMIN',
  CONTENT_MODERATOR = 'CONTENT MODERATOR',
  CURATOR = 'CURATOR',
  SUPPORT_STAFF = 'SUPPORT STAFF',
  COMMERCE_MANAGER = 'COMMERCE MANAGER'
}
